run:
  tests: false
  skip-dirs:
    - generated

linters-settings:
  funlen:
    lines: 70
    statements: 40

  lll:
    line-length: 150
    tab-width: 1

  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - golint # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - wsl # strange behavior
    - paralleltest # strange behavior
    - exhaustivestruct # strange behavior
    - tagliatelle # strange behavior
    - ifshort # strange behavior
    - dogsled # strange behavior
    - wrapcheck # strange behavior
    - exhaustive # strange behavior
    - errorlint # strange behavior
    - revive # strange behavior
    - gci # strange behavior
  fast: false
