run:
  tests: false

linters-settings:
  lll:
    line-length: 130
    tab-width: 1

  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - golint # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - wsl # strange behavior
    - paralleltest # strange behavior
    - exhaustivestruct # strange behavior
    - tagliatelle # strange behavior
  fast: false
