// Code generated by MockGen. DO NOT EDIT.
// Source: grpc.go

// Package rpc_test is a generated GoMock package.
package rpc_test

import (
	context "context"
	json "encoding/json"
	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// Mockfiles is a mock of files interface
type Mockfiles struct {
	ctrl     *gomock.Controller
	recorder *MockfilesMockRecorder
}

// MockfilesMockRecorder is the mock recorder for Mockfiles
type MockfilesMockRecorder struct {
	mock *Mockfiles
}

// NewMockfiles creates a new mock instance
func NewMockfiles(ctrl *gomock.Controller) *Mockfiles {
	mock := &Mockfiles{ctrl: ctrl}
	mock.recorder = &MockfilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockfiles) EXPECT() *MockfilesMockRecorder {
	return m.recorder
}

// UploadFile mocks base method
func (m *Mockfiles) UploadFile(ctx context.Context, file io.Reader) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile
func (mr *MockfilesMockRecorder) UploadFile(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*Mockfiles)(nil).UploadFile), ctx, file)
}

// SetMetadata mocks base method
func (m *Mockfiles) SetMetadata(ctx context.Context, fileID uuid.UUID, metadata json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetadata", ctx, fileID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMetadata indicates an expected call of SetMetadata
func (mr *MockfilesMockRecorder) SetMetadata(ctx, fileID, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetadata", reflect.TypeOf((*Mockfiles)(nil).SetMetadata), ctx, fileID, metadata)
}

// Delete mocks base method
func (m *Mockfiles) Delete(ctx context.Context, fileID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockfilesMockRecorder) Delete(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockfiles)(nil).Delete), ctx, fileID)
}
