// Code generated by MockGen. DO NOT EDIT.
// Source: grpc.go

// Package rpc_test is a generated GoMock package.
package rpc_test

import (
	context "context"
	app "github.com/Meat-Hook/back-template/internal/modules/user/internal/app"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Mockusers is a mock of users interface
type Mockusers struct {
	ctrl     *gomock.Controller
	recorder *MockusersMockRecorder
}

// MockusersMockRecorder is the mock recorder for Mockusers
type MockusersMockRecorder struct {
	mock *Mockusers
}

// NewMockusers creates a new mock instance
func NewMockusers(ctrl *gomock.Controller) *Mockusers {
	mock := &Mockusers{ctrl: ctrl}
	mock.recorder = &MockusersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockusers) EXPECT() *MockusersMockRecorder {
	return m.recorder
}

// UserByID mocks base method
func (m *Mockusers) UserByID(ctx context.Context, session app.Session, id int) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, session, id)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID
func (mr *MockusersMockRecorder) UserByID(ctx, session, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*Mockusers)(nil).UserByID), ctx, session, id)
}
