// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package file_test is a generated GoMock package.
package file_test

import (
	context "context"
	io "io"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
)

// MockfileSvc is a mock of fileSvc interface.
type MockfileSvc struct {
	ctrl     *gomock.Controller
	recorder *MockfileSvcMockRecorder
}

// MockfileSvcMockRecorder is the mock recorder for MockfileSvc.
type MockfileSvcMockRecorder struct {
	mock *MockfileSvc
}

// NewMockfileSvc creates a new mock instance.
func NewMockfileSvc(ctrl *gomock.Controller) *MockfileSvc {
	mock := &MockfileSvc{ctrl: ctrl}
	mock.recorder = &MockfileSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileSvc) EXPECT() *MockfileSvcMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockfileSvc) Delete(ctx context.Context, fileID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockfileSvcMockRecorder) Delete(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockfileSvc)(nil).Delete), ctx, fileID)
}

// Upload mocks base method.
func (m *MockfileSvc) Upload(ctx context.Context, r io.Reader) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockfileSvcMockRecorder) Upload(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockfileSvc)(nil).Upload), ctx, r)
}
