#!/bin/bash

# For MacOS.
if test "$(uname)" = "Darwin"; then
  shopt -s expand_aliases
  alias sed=gsed
  alias grep=ggrep
  alias xargs=gxargs
fi

# Start Dockerfile linter.
hadolint Dockerfile

# Start shel linter.
shellcheck env.sh.dist scripts/*

# Start buf lint.
buf lint
# Start golang linter.
golangci-lint run
# Start buf breaking check.
buf breaking --against '.git#branch=master'
# Start golang test.
gotestsum -- -race "$@" ./...
